# this config was migrated from renv.lock on 2026-09-15
[project]
name = "lyme-disease"
r_version = "4.6"

repositories = [
    { alias = "CRAN", url = "https://cran.rstudio.com/"}
]

dependencies = [
    { name = "PKI", repository = "CRAN" },
    { name = "R6", repository = "CRAN" },
    { name = "RColorBrewer", repository = "CRAN" },
    { name = "RcppTOML", repository = "CRAN" },
    { name = "TTR", repository = "CRAN" },
    { name = "askpass", repository = "CRAN" },
    { name = "assertthat", repository = "CRAN" },
    { name = "base64enc", repository = "CRAN" },
    { name = "bit", repository = "CRAN" },
    { name = "brand.yml", repository = "CRAN" },
    { name = "bslib", repository = "CRAN" },
    { name = "cachem", repository = "CRAN" },
    { name = "cellranger", repository = "CRAN" },
    { name = "classInt", repository = "CRAN" },
    { name = "cli", repository = "CRAN" },
    { name = "commonmark", repository = "CRAN" },
    { name = "conflicted", repository = "CRAN" },
    { name = "crayon", repository = "CRAN" },
    { name = "crul", repository = "CRAN" },
    { name = "digest", repository = "CRAN" },
    { name = "evaluate", repository = "CRAN" },
    { name = "farver", repository = "CRAN" },
    { name = "fastmap", repository = "CRAN" },
    { name = "fontawesome", repository = "CRAN" },
    { name = "forcats", repository = "CRAN" },
    { name = "fs", repository = "CRAN" },
    { name = "generics", repository = "CRAN" },
    { name = "geojson", repository = "CRAN" },
    { name = "geojsonio", repository = "CRAN" },
    { name = "geojsonsf", repository = "CRAN" },
    { name = "geometries", repository = "CRAN" },
    { name = "googledrive", repository = "CRAN" },
    { name = "googlesheets4", repository = "CRAN" },
    { name = "gtable", repository = "CRAN" },
    { name = "haven", repository = "CRAN" },
    { name = "hms", repository = "CRAN" },
    { name = "htmltools", repository = "CRAN" },
    { name = "htmlwidgets", repository = "CRAN" },
    { name = "httpcode", repository = "CRAN" },
    { name = "ids", repository = "CRAN" },
    { name = "janitor", repository = "CRAN" },
    { name = "jqr", repository = "CRAN" },
    { name = "jquerylib", repository = "CRAN" },
    { name = "jsonify", repository = "CRAN" },
    { name = "jsonlite", repository = "CRAN" },
    { name = "labeling", repository = "CRAN" },
    { name = "lifecycle", repository = "CRAN" },
    { name = "memoise", repository = "CRAN" },
    { name = "mime", repository = "CRAN" },
    { name = "modelr", repository = "CRAN" },
    { name = "otel", repository = "CRAN" },
    { name = "packrat", repository = "CRAN" },
    { name = "pillar", repository = "CRAN" },
    { name = "pkgconfig", repository = "CRAN" },
    { name = "prettyunits", repository = "CRAN" },
    { name = "progress", repository = "CRAN" },
    { name = "promises", repository = "CRAN" },
    { name = "rapidjsonr", repository = "CRAN" },
    { name = "rappdirs", repository = "CRAN" },
    { name = "rematch", repository = "CRAN" },
    { name = "rematch2", repository = "CRAN" },
    { name = "reprex", repository = "CRAN" },
    { name = "rjson", repository = "CRAN" },
    { name = "rlang", repository = "CRAN" },
    { name = "rlist", repository = "CRAN" },
    { name = "rvest", repository = "CRAN" },
    { name = "sass", repository = "CRAN" },
    { name = "scales", repository = "CRAN" },
    { name = "sfheaders", repository = "CRAN" },
    { name = "shinycssloaders", repository = "CRAN" },
    { name = "slbrand", git = "https://github.com/shelbylevel/slbrand", commit = "c99fdebcb3fd5b7a1e591e1b89c7ca3a0648a191" },
    { name = "snakecase", repository = "CRAN" },
    { name = "stringr", repository = "CRAN" },
    { name = "sys", repository = "CRAN" },
    { name = "tidyselect", repository = "CRAN" },
    { name = "tidyverse", repository = "CRAN" },
    { name = "tigris", repository = "CRAN" },
    { name = "triebeard", repository = "CRAN" },
    { name = "tzdb", repository = "CRAN" },
    { name = "urltools", repository = "CRAN" },
    { name = "utf8", repository = "CRAN" },
    { name = "yaml", repository = "CRAN" },
]
